import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link';


import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="container mx-auto flex items-center justify-between">
          <h1 className="text-xl font-bold">Mon Portfolio</h1>
          <nav>
            <ul className="flex space-x-4">
              <li><Link href="/">
                Accueil
              </Link>
              </li>
              <li><Link href="/aPropos">
                A Propos de moi
              </Link>
              </li>
              <li><Link href="/contact">
                Contactez moi
              </Link>
              </li>
            </ul>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
